#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/pete/.local/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/pete/.local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/pete/Desktop/NeuroResearch/cells/CA3_both_modules/x86_64/.libs/libnrnmech.so" "$@"
